name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scalaVersion: ['2.12.14', '2.13.6', '3.0.1']
        javaTag: ['8u302', '11.0.12', '16.0.2', '11.0.12-oraclelinux8', 'graalvm-ce-21.2.0-java11', 'graalvm-ce-21.2.0-java8', 'graalvm-ce-21.2.0-java16']
        include:
          - javaTag: '8u302'
            dockerContext: 'debian'
            baseImageTag: '8u302-jdk-buster'
          - javaTag: '11.0.12'
            dockerContext: 'debian'
            baseImageTag: '11.0.12-jdk-buster'
          - javaTag: '16.0.2'
            dockerContext: 'debian'
            baseImageTag: '16.0.2-jdk-buster'
          - javaTag: '11.0.12-oraclelinux8'
            dockerContext: 'oracle'
            baseImageTag: '11.0.12-jdk-oraclelinux8'
          - javaTag: 'graalvm-ce-21.2.0-java11'
            dockerContext: 'graalvm-ce'
            baseImageTag: 'java11-21.2.0'
          - javaTag: 'graalvm-ce-21.2.0-java8'
            dockerContext: 'graalvm-ce'
            baseImageTag: 'java8-21.2.0'
          - javaTag: 'graalvm-ce-21.2.0-java16'
            dockerContext: 'graalvm-ce'
            baseImageTag: 'java16-21.2.0'
    steps:
    - uses: actions/checkout@v1
    - name: Get latest SBT version
      id: get_sbt_version
      run: |
        SBT_VERSION=$(
          curl -s curl -L https://github.com/sbt/sbt/releases |
          grep -i -w 'sbt-[0-9]*\.[0-9]*\.[0-9]*\.tgz' -o |
          grep -i -w '[0-9]*\.[0-9]*\.[0-9]*' -o |
          sort -V | tail -n 1)
        echo ::set-output name=VERSION::$SBT_VERSION
    - name: Create docker tag
      id: create_docker_tag
      run: |
        TAG=hseeberger/scala-sbt:${{ matrix.javaTag }}_${{ steps.get_sbt_version.outputs.VERSION }}_${{ matrix.scalaVersion }}
        echo ::set-output name=TAG::$TAG
    - name: Build docker image
      run: |
        docker build ${{ matrix.dockerContext }} \
            --no-cache \
            -t "${{ steps.create_docker_tag.outputs.TAG }}" \
            --build-arg BASE_IMAGE_TAG=${{ matrix.baseImageTag }} \
            --build-arg SBT_VERSION=${{ steps.get_sbt_version.outputs.VERSION }} \
            --build-arg SCALA_VERSION=${{ matrix.scalaVersion }}
    - name: Test docker image as root (default)
      if: ${{ !startsWith(matrix.scalaVersion, '2.12') }}
      # scala --version does not work on < 2.13
      run: |
        docker run "${{ steps.create_docker_tag.outputs.TAG }}" \
          scala --version &&
          sbt about
    - name: Test docker image scala as sbtuser
      if: ${{ !startsWith(matrix.scalaVersion, '2.12') }}
      # scala --version does not work on < 2.13
      run: |
        docker run -u sbtuser -w /home/sbtuser "${{ steps.create_docker_tag.outputs.TAG }}" \
          scala --version &&
          sbt about
    - name: Push image to DockerHub
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u hseeberger --password-stdin
        docker push ${{ steps.create_docker_tag.outputs.TAG }}
